package rules

import com.masterthesis.alertingsystem.rules.facts.MetricData
import com.masterthesis.alertingsystem.rules.facts.AlertResult

global java.util.Map thresholds;

rule "Check if metric exceeds threshold"
when
    $metricData : MetricData($name : name, $value : value)
    $metricThresholds : Map() from thresholds[$name]
    $threshold : Double() from $metricThresholds["max"]
    eval($value > $threshold)
then
    System.out.println(">> ALERT: Metric '" + $name + "' exceeded threshold (" + $value + " > " + $threshold + ")");
    AlertResult result = new AlertResult();
    result.setThresholdExceeded(true);
    insert(result);
end
